### ISSUE TITLE
error: certikd export

### ISSUE THREAD

**Issue by pkrasam** [certikfoundation/chain#11]
In preparation for the upcoming hardfork, I am following the instructions and on step 3...

C:
```
certikd export --for-zero-height --height 191300 > genesis_old.json
```
E:
```
ERROR: couldn't create db: Error initializing DB: resource temporarily unavailable
```
Reference: https://github.com/certikfoundation/chain/releases/tag/v0.11

**Comment by yoongbok-lee** [comment]
The command will be functional when the chain reaches 191300 & the daemon is synced up to that height. You can test if it works correctly with smaller number for --height flag.

**Comment by yoongbok-lee** [comment]
Forgot to note that you need to stop certikd process before that command as well
