### ISSUE TITLE
error: curl for new genesis time

### ISSUE THREAD

**Issue by pkrasam** [certikfoundation/chain#13]
The curl command is failing on step 4

C:
```
curl https://certik-shentu-incentivized-vermilionbird.noopsbycertik.com/blocks/191300
```
E:
```
{"error":"requested block height is bigger then the chain length"
```
Reference: https://github.com/certikfoundation/chain/releases/tag/v0.11

**Comment by yoongbok-lee** [comment]
Yes, the command will be functional after the chain reaches block height 191300. You can test if the query works with smaller block height.
