### ISSUE TITLE
ERROR: unknown address: account certik149qw... does not exist

### ISSUE THREAD

**Issue by majal** [certikfoundation/chain#6]
Hi!

I tried running the validator node and all things seemed to work well based on the procedure, except on this last stage of the command:

`$  ./certikcli tx staking create-validator --amount 2000000uctk --commission-max-change-rate 0.1 --commission-max-rate 0.2 --commission-rate 0.1 --from <local wallet name> --min-self-delegation 1 --moniker <validator name> --pubkey certikvalconspub1zcjduepqrwt64kzpnrdmweh9uljyfakj3qr2tf7p23jp7ryk6lz9e4ve9pasz2akqr --chain-id shentu-incentivized --fees 1600uctk`

It throws this error:

`ERROR: unknown address: account certik149qw... does not exist`

Well it appears that the local wallet exists when this command is run

`$  ./certikcli keys show <local wallet name>`

It even shows that address where the name is connected.

Any nudge to the right place? Thanks a lot!

**Comment by joesixpack** [comment]
That happens when your wallet and/or validator name is not found or wrong.

Did you certify your validator key?

**Comment by majal** [comment]
Hi @joesixpack! Thanks for giving this your attention. I had help from the Telegram group and the problem was that **my local chain has not fully synced yet after 5+ hours.** I'll have to wait for it to be fully synched before it will see the new wallet that was created. It's okay now, the validator can be found here:

[https://explorer.certik.foundation/validators/certikvaloper149qwmajcwwlnc7m9jgqd5yqv9a546kwmhkzmxa](https://explorer.certik.foundation/validators/certikvaloper149qwmajcwwlnc7m9jgqd5yqv9a546kwmhkzmxa)

Thanks for taking the time. Have a good day!
